const initialRows = [
  {
    id: 1,
    name: 'Product 1',
    type: 'Type 1',
    price: 20.5,
    available: true,
    quantity: 1,
  },
  {
    id: 2,
    name: 'Product 2',
    type: 'Type 2',
    price: 15.75,
    available: false,
    quantity: 0,
  },
  {
    id: 3,
    name: 'Product 3',
    type: 'Type 1',
    price: 18.25,
    available: true,
    quantity: 3,
  },
  {
    id: 4,
    name: 'Product 4',
    type: 'Type 2',
    price: 22.0,
    available: true,
    quantity: 5,
  },
  {
    id: 5,
    name: 'Product 5',
    type: 'Type 1',
    price: 14.99,
    available: false,
    quantity: 0,
  },
  {
    id: 6,
    name: 'Product 6',
    type: 'Type 3',
    price: 30.5,
    available: true,
    quantity: 2,
  },
  {
    id: 7,
    name: 'Product 7',
    type: 'Type 2',
    price: 17.75,
    available: false,
    quantity: 0,
  },
  {
    id: 8,
    name: 'Product 8',
    type: 'Type 1',
    price: 25.99,
    available: true,
    quantity: 10,
  },
  {
    id: 9,
    name: 'Product 9',
    type: 'Type 3',
    price: 12.0,
    available: true,
    quantity: 4,
  },
  {
    id: 10,
    name: 'Product 10',
    type: 'Type 2',
    price: 19.5,
    available: true,
    quantity: 7,
  },
  {
    id: 11,
    name: 'Product 11',
    type: 'Type 1',
    price: 16.75,
    available: false,
    quantity: 0,
  },
  {
    id: 12,
    name: 'Product 12',
    type: 'Type 3',
    price: 27.25,
    available: true,
    quantity: 6,
  },
  {
    id: 13,
    name: 'Product 13',
    type: 'Type 1',
    price: 20.0,
    available: true,
    quantity: 2,
  },
  {
    id: 14,
    name: 'Product 14',
    type: 'Type 2',
    price: 15.25,
    available: false,
    quantity: 0,
  },
  {
    id: 15,
    name: 'Product 15',
    type: 'Type 3',
    price: 23.99,
    available: true,
    quantity: 8,
  },
  {
    id: 16,
    name: 'Product 16',
    type: 'Type 1',
    price: 14.5,
    available: true,
    quantity: 3,
  },
  {
    id: 17,
    name: 'Product 17',
    type: 'Type 2',
    price: 21.75,
    available: true,
    quantity: 5,
  },
  {
    id: 18,
    name: 'Product 18',
    type: 'Type 3',
    price: 18.0,
    available: false,
    quantity: 0,
  },
  {
    id: 19,
    name: 'Product 19',
    type: 'Type 1',
    price: 32.5,
    available: true,
    quantity: 12,
  },
  {
    id: 20,
    name: 'Product 20',
    type: 'Type 2',
    price: 26.99,
    available: true,
    quantity: 9,
  },
  {
    id: 21,
    name: 'Product 21',
    type: 'Type 3',
    price: 15.0,
    available: true,
    quantity: 1,
  },
  {
    id: 22,
    name: 'Product 22',
    type: 'Type 1',
    price: 23.75,
    available: false,
    quantity: 0,
  },
  {
    id: 23,
    name: 'Product 23',
    type: 'Type 2',
    price: 28.5,
    available: true,
    quantity: 6,
  },
];

export default initialRows;
